name: favicon
description: Library for finding favicons in a website, either in a <link> or by predefined URL.
version: 1.0.14
homepage: https://github.com/marcjoha/favicon

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.13.0
  html: ^0.15.0
  image: ^3.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.16.5
