name: favicon
description: Library for finding favicons in a website, either in a <link> or by predefined URL.
version: 1.0.11
homepage: https://github.com/marcjoha/favicon

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  html: ^0.14.0+3
  image: ^2.1.12

dev_dependencies:
  pedantic: ^1.8.0
